DROP TABLE human CASCADE;
DROP TABLE engine CASCADE;
DROP TABLE human_to_engine CASCADE;
DROP TABLE antenna CASCADE;
DROP TABLE human_to_antenna CASCADE;
DROP TABLE spaceship CASCADE;
DROP TABLE hal CASCADE;
